name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v3

    - name: Pull Docker image from Docker Hub
      run: docker pull mpk31415/ubuntu-clang-amd
    
    - name: Compile and run tests
      run: docker run mpk31415/ubuntu-clang-amd /bin/bash -c "./run_tests.sh"
